name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region ap-northeast-2 | \
        docker login --username AWS --password-stdin 866874933972.dkr.ecr.ap-northeast-2.amazonaws.com

    - name: Build and push Docker image
      run: |
        docker build -t hello-ecr .
        docker tag hello-ecr:latest 866874933972.dkr.ecr.ap-northeast-2.amazonaws.com/hello-ecr:latest
        docker push 866874933972.dkr.ecr.ap-northeast-2.amazonaws.com/hello-ecr:latest

    - name: Deploy to ECS
      run: |
        aws ecs update-service \
          --cluster hello-cluster \
          --service hello-task-ecs-serv \
          --force-new-deployment

